export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const SET_USER_ACCOUNT_BALANCE = 'SET_USER_ACCOUNT_BALANCE';
export const UPDATE_USER_ACCOUNT_BALANCE = 'UPDATE_USER_ACCOUNT_BALANCE';
