export const STATE_USER_STORAGE_KEY = 'user'
export const STATE_GAMES_STORAGE_KEY = 'games'
export const LINKEDIN_LINK = 'https://www.linkedin.com/in/wojciech-guze'
export const GITHUB_LINK = 'https://github.com/wojciechguze2'
export const MAIL_LINK = 'mailto:wojciechguze2@gmail.com'
export const PHONE_LINK = 'tel:+48518118593'
